apiVersion: batch/v1
kind: CronJob
metadata:
  name: alias-computation
  labels:
    cronLastSuccessfulTimeMins: 45
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alias-computation
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
