apiVersion: batch/v1
kind: CronJob
metadata:
  name: debian-convert
  labels:
    cronLastSuccessfulTimeMins: 180
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: debian-convert
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
            - name: OUTPUT_GCS_BUCKET
              value: osv-test-debian-osv
